server:
  port: 9090
  servlet:
    context-path: /fom
spring:
  application:
      name: fom
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.108.11.132:3306/fom?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: anji-plus
    password: anji-plus
    type: com.alibaba.druid.pool.DruidDataSource
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
#mybatis:
#  dao-locations: classpath:mapper/*.xml
#  type-aliases-package: com.cl.entity
#showSql
#logging:
#  level:
#    com.cl.dao: debug

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cl.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    capital-mode: true
    logic-delete-value: 0
    logic-not-delete-value: 1

interface:
  app:
    id: F0005mauBUF
    secure: nuX8Vj6ZcY
    uri : /platform/order/queryProduceOrderInfo
  private: 
    key: MIIBVgIBADANBgkqhkiG9w0BAQEFAASCAUAwggE8AgEAAkEApJ5OxE1EpZVq9bz6BHzsbBEsgIv4Kmn1Ana5jDY3S4ClQvKM3I2eWPP5AlMGg7SsMH8890xjxS9hchGAk5T0jwIDAQABAkEAnV08HMlkewmX4uvQ8SNeenv8V7H1/M2nSsCl5RQazc/XGs4v1YZMgYohVGA/rI6ing7nLut9sMtzLK+VjOHzgQIhANF15Itiqy0eLMEMXnakT/K7nZFBWsYnU3vuKFynwUJBAiEAyTHLz1KS/jj3I4C9F0FYCTBbX/fzUj2HaMDJ7KcT4s8CIQCK/zL0lDuHqziDuxOMo6kyKPJ9C+OTD1HFMduy8Ne8gQIhAJ0uSguudyglWO5jpVaFtkF3hetzyqR1bVRpSVeZL/ABAiBh4S6+k9oInL9TXZcv6lH2pKeovA1zkN/bZZSlcDWEEg==
  url: 
    prefix: http://mes-sit01.020mes.com
