server:
  port: 8080
  servlet:
    context-path: /fom
spring:
  application:
      name: fom
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zl?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: Chen1203!
    type: com.alibaba.druid.pool.DruidDataSource
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cl.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    capital-mode: true
    logic-delete-value: 0
    logic-not-delete-value: 1

interface:
  app:
    id: 'F0021XXbckE'
    secure: 'cifDBnrI9g'
    uri : /platform/order/queryProduceOrderInfo
  private: 
    key: MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEAmXIqBJmSThV/RDteVjNnH06xHceFR7C/z/2RStNbgLS6qTo0rThqBn/zFkNmj92Sipcd6YRQGgxr1l7SEAtnNQIDAQABAkAtW12oNmzUv+36kUH1YQRecLhSASQYaNqJ9H36DDfD9y9/j3i5UvkJfAK6cKJRo/ew8X97cwIMeydx91/Lx/6RAiEA/LoYxuqpYqbqCw5cqjpgd7wCY7/DbUwTg+Y9rNZpkusCIQCbbugE7bJBTTq4bLafjFOyqT8JLQz7+Pv5DL4Cj20mXwIhAI5mUVWrnVuPzyoBoqbsE7UDg5ku0O/BwPE+BxxfB8eXAiBKuYf8DpY7BLjtPv6RN7JpWyp969WpMatZsUGME44C+wIhAORGeGLp8EgdcXnrU8nKc5kZbheHp/+VOm2EldmUFQ+w
  url: 
    prefix: https://www.020mes.com
    
dashboard:
  show:
    day: 5
  purchase:
    start_date: 2
    difference: 2
  tailor:
    start_date: 2
    difference: 4


logging:
  level:
    root: info
  file: log/fom.log
  # 默认日志路径
  #path: ./log

