server:
  port: 9090
  servlet:
    context-path: /fom
spring:
  application:
      name: fom
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zl?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: Chen1203!
    type: com.alibaba.druid.pool.DruidDataSource
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cl.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    capital-mode: true
    logic-delete-value: 0
    logic-not-delete-value: 1

interface:
#  app:
#    id: F0005mauBUF
#    secure: nuX8Vj6ZcY
#    uri : /platform/order/queryProduceOrderInfo
#  private: 
#    key: MIIBVgIBADANBgkqhkiG9w0BAQEFAASCAUAwggE8AgEAAkEApJ5OxE1EpZVq9bz6BHzsbBEsgIv4Kmn1Ana5jDY3S4ClQvKM3I2eWPP5AlMGg7SsMH8890xjxS9hchGAk5T0jwIDAQABAkEAnV08HMlkewmX4uvQ8SNeenv8V7H1/M2nSsCl5RQazc/XGs4v1YZMgYohVGA/rI6ing7nLut9sMtzLK+VjOHzgQIhANF15Itiqy0eLMEMXnakT/K7nZFBWsYnU3vuKFynwUJBAiEAyTHLz1KS/jj3I4C9F0FYCTBbX/fzUj2HaMDJ7KcT4s8CIQCK/zL0lDuHqziDuxOMo6kyKPJ9C+OTD1HFMduy8Ne8gQIhAJ0uSguudyglWO5jpVaFtkF3hetzyqR1bVRpSVeZL/ABAiBh4S6+k9oInL9TXZcv6lH2pKeovA1zkN/bZZSlcDWEEg==
#  url: 
#    prefix: http://mes-sit01.020mes.com
  app:
    id: 'F0005FqG*bC'
    secure: 'vvjfBa#8XR'
    uri : /platform/order/queryProduceOrderInfo
  private: 
    key: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAoctb4JxWViUVUdTBRH2WE1vLmBqo/tcayUcbG2jwGKNvVfty6SuOEer8onYz2m/SV2HnMkX0i4/1XZCo5t6GTwIDAQABAkAUQOzDdU6pggLlN4jqFf6PddJKvCujmzHTOH+AMua7bqcespYx+FD4C3/xcz9BMJdNaut5nVMdWf5V3FNpNXGhAiEA1p+4x/n88iPzJAApUdjQICL3Xvn1cVQiX7nuDhxsyA0CIQDA/Fq6xMpp/c4oXM1sKlGrhtnXVl7YAjir/GwFFk50ywIgcuUWepetfcMZCpC7jgFPiaSuYL3XU1ADBtP2SL+WzJECICcewLGdlL6ZoYHTFh04EugnZN9e9cjp4l0SxT7ev7azAiEAt09Yog0VBI0OjpF/basZhyqWPPU3iPb//M18rR3He6k=
  url: 
    prefix: https://www.020mes.com
    
dashboard:
  show:
    day: 5
  purchase:
    difference: 5
  tailor:
    difference: 3


logging:
  level:
    root: info
  file: log/fom.log
  # 默认日志路径
  #path: ./log