server:
  port: 9090
  servlet:
    context-path: /fom
spring:
  application:
      name: fom
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.108.11.132:3306/fom?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: anji-plus
    password: anji-plus
    type: com.alibaba.druid.pool.DruidDataSource
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
#mybatis:
#  dao-locations: classpath:mapper/*.xml
#  type-aliases-package: com.cl.entity
#showSql
#logging:
#  level:
#    com.cl.dao: debug

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cl.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    capital-mode: true
    logic-delete-value: 0
    logic-not-delete-value: 1


